### ISSUE TITLE
dimension error again!!!

### ISSUE THREAD

**Issue by Chu-Orion** [hzxie/Pix2Vox#102]
I'm sorry to bother you again, but after downgrading to version 3.0.3, the same error still occurs

Traceback (most recent call last):
File "F:\PyCharm\Pix2Vox-master\runner.py", line 93, in
main()
File "F:\PyCharm\Pix2Vox-master\runner.py", line 74, in main
train_net(cfg)
File "F:\PyCharm\Pix2Vox-master\core\train.py", line 268, in train_net
iou = test_net(cfg, epoch_idx + 1, output_dir, val_data_loader, val_writer, encoder, decoder, refiner, merger)
File "F:\PyCharm\Pix2Vox-master\core\test.py", line 152, in test_net
epoch_idx)
File "F:\PyCharm\Pix2Vox-master\utils\binvox_visualization.py", line 20, in get_volume_views
ax.voxels(volume, edgecolor="k")
File "D:\SoftWare\Anaconda3\envs\pytorch\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 2866, in voxels
raise ValueError("Argument filled must be 3-dimensional")
ValueError: Argument filled must be 3-dimensional
[INFO/MainProcess] process shutting down

**Comment by hzxie** [comment]
Sorry, I cannot reproduce the error.

**Comment by Chu-Orion** [comment]
I've tackled this problem!!!! As it turns out, it was my conda that was the problem. Thank you all the time!!!
