### ISSUE TITLE
用ShapeNet数据集进行训练，在即将迭代完一次后出现以下错误。

### ISSUE THREAD

**Issue by saisai1002** [hzxie/Pix2Vox#14]
[INFO] 2019-11-18 20:14:12.342971 [Epoch 1/250][Batch 478/478] BatchTime = 0.641 (s) DataTime = 0.000 (s) EDLoss = 1.6889 RLoss = 1.5908
[INFO/Process-1] process shutting down
[INFO/Process-2] process shutting down
[INFO/Process-3] process shutting down
[INFO/Process-1] process exiting with exitcode 0
[INFO/Process-2] process exiting with exitcode 0
[INFO/Process-4] process shutting down
[INFO/Process-3] process exiting with exitcode 0
[INFO/Process-4] process exiting with exitcode 0
[INFO] 2019-11-18 20:14:12.717975 Epoch [1/250] EpochTime = 364.328 (s) EDLoss = 2.7254 RLoss = 2.1918
[INFO/Process-5] child process calling self.run()
[INFO/Process-5] process shutting down
[INFO/Process-5] process exiting with exitcode 0
Traceback (most recent call last):
  File "C:\Users\A409\AppData\Roaming\Python\Python35\site-packages\PIL\Image.py", line 2645, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 389), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\runner.py", line 87, in <module>
    main()
  File ".\runner.py", line 68, in main
    train_net(cfg)
  File "D:\lisaisai\Pix2Vox-master\core\train.py", line 261, in train_net
    iou = test_net(cfg, epoch_idx + 1, output_dir, val_data_loader, val_writer, encoder, decoder, refiner, merger)
  File "D:\lisaisai\Pix2Vox-master\core\test.py", line 150, in test_net
    test_writer.add_image('Test Sample#%02d/Volume Reconstructed' % sample_idx, rendering_views, epoch_idx)
  File "C:\Users\A409\AppData\Roaming\Python\Python35\site-packages\tensorboardX\writer.py", line 584, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "C:\Users\A409\AppData\Roaming\Python\Python35\site-packages\tensorboardX\summary.py", line 271, in image
    image = make_image(tensor, rescale=rescale)
  File "C:\Users\A409\AppData\Roaming\Python\Python35\site-packages\tensorboardX\summary.py", line 311, in make_image
    image = Image.fromarray(tensor)
  File "C:\Users\A409\AppData\Roaming\Python\Python35\site-packages\PIL\Image.py", line 2647, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
[INFO/MainProcess] process shutting down

**Comment by hzxie** [comment]
Please downgrade your TensorBoardX to 1.2.0.

**Comment by saisai1002** [comment]
谢谢，已解决！
