### ISSUE TITLE
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

### ISSUE THREAD

**Issue by saisai1002** [hzxie/Pix2Vox#35]
![image](https://user-images.githubusercontent.com/23035261/83127143-6686a100-a10c-11ea-8523-fe43523debf1.png)
hello, This is my problem.can you help me..?thanks

**Comment by saisai1002** [comment]
[INFO] 2020-05-28 09:18:19.904704 [Epoch 1/250][Batch 478/478] BatchTime = 4.252 (s) DataTime = 3.712 (s) EDLoss = 1.5016 RLoss = 1.4882
[INFO] 2020-05-28 09:18:19.906029 Epoch [1/250] EpochTime = 2111.654 (s) EDLoss = 1.6588 RLoss = 1.6884
[INFO/Process-1] child process calling self.run()
[INFO/Process-1] created temp directory /tmp/pymp-yb0ta8fk
[INFO/Process-1] process shutting down
[INFO/Process-1] process exiting with exitcode 0
Traceback (most recent call last):
  File "runner.py", line 93, in <module>
    main()
  File "runner.py", line 74, in main
    train_net(cfg)
  File "/home/baijinggroup/lss/Pix2Vox/core/train.py", line 264, in train_net
    iou = test_net(cfg, epoch_idx + 1, output_dir, val_data_loader, val_writer, encoder, decoder, refiner, merger)
  File "/home/baijinggroup/lss/Pix2Vox/core/test.py", line 151, in test_net
    epoch_idx)
  File "/home/baijinggroup/lss/Pix2Vox/utils/binvox_visualization.py", line 19, in get_volume_views
    ax.set_aspect('equal')
  File "/home/baijinggroup/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

**Comment by hzxie** [comment]
Please check your version of matplotlib.
See also https://github.com/hzxie/Pix2Vox/issues/13
