### ISSUE TITLE
Error when train using runner.py

### ISSUE THREAD

**Issue by suhailsola** [hzxie/Pix2Vox#64]
I tried to train the using the 'runner.py' but it came out with this.

File "C:\Users\Ilham\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboardX\record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: 'output\\logs\\2021-02-08T00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ilham\Downloads\Pix2Vox\runner.py", line 93, in <module>
    main()
  File "C:\Users\Ilham\Downloads\Pix2Vox\runner.py", line 74, in main
    train_net(cfg)
  File "C:\Users\Ilham\Downloads\Pix2Vox\core\train.py", line 161, in train_net
    train_writer = SummaryWriter(os.path.join(log_dir, "train"))
  File "C:\Users\Ilham\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboardX\writer.py", line 275, in __init__
    self._get_file_writer()
  File "C:\Users\Ilham\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboardX\writer.py", line 323, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir,
  File "C:\Users\Ilham\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboardX\writer.py", line 94, in __init__
    self.event_writer = EventFileWriter(
  File "C:\Users\Ilham\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboardX\event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "C:\Users\Ilham\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboardX\record_writer.py", line 51, in directory_check
    os.makedirs(path)
  File "C:\Users\Ilham\AppData\Local\Programs\Python\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Ilham\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'output\\logs\\2021-02-08T00:00:21.602524'
[INFO/MainProcess] process shutting down

**Comment by hzxie** [comment]
Change:

https://github.com/hzxie/Pix2Vox/blob/f1b82823e79d4afeedddfadb3da0940bcf1c536d/core/train.py#L157

to

```py
    output_dir = os.path.join(cfg.DIR.OUT_PATH, '%s', dt.now().isoformat().replace(':', '-')) 
```

Because on Windows, the file name can not contains `:`.
